### ISSUE TITLE
Allow passing environment variables to the orb

### ISSUE THREAD

**Issue by ghost** [anchore/circleci-orb-grype#5]
**What would you like to be added**:
Environment Variables should be able to be used from the job passed to the orb

**Why is this needed**:
Its a common use case in the event that you dont want to hardcode an image tag, but instead use something like ${CIRCLE_SHA1} if your images are tagged with ${CIRCLE_SHA1}
**Additional context**:

Example configuration that results in a failure because the orb doesn't interpolate the variable:

```
orbs:
  grype: anchore/grype@0.26.1

jobs:
  grype_vuln_scan:
    description: "Uses grype orb for vuln scans"
    docker:
      - image: circleci/python:3.8
    steps:
    - grype/scan-image:
        image-name: some/repo:${CIRCLE_SHA1}
        output-format: "table"
workflows:
  default_workflow:
    jobs:
      - grype_vuln_scan:
```
